<?php
require __DIR__.'/../include/session.php';
try{$officer=currentAccountOfficer();$csrf=accountCsrfToken($officer);$error='';}catch(Throwable){$officer=null;$csrf='';$error='Authorized Account Officer identity required.';}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Account Office | Refund Crediting</title><link rel="stylesheet" href="../assets/css/accountofficer.css"></head><body>
<div class="app-shell"><aside class="sidebar"><div class="brand"><img src="../../cu_studentaffairs/assets/images/university-logo.png" alt="Covenant University"><div><strong>Covenant</strong><span>University</span></div></div><nav><a class="nav-link active" href="dashboard.php">Refund Crediting</a></nav></aside><main class="content"><header class="topbar"><div><p>Account Office / Replacement ID Card Portal</p><h1>Approved Refunds Awaiting Credit</h1></div><span class="officer-badge"><?=htmlspecialchars($officer?->id??'Not signed in')?></span></header><?php if($error):?><div class="notice show error"><?=$error?></div><?php endif;?><div id="notice" class="notice"></div>
<section class="applications-container"><div class="toolbar"><input id="search" type="search" placeholder="Search reference, matric, or student name"><label>Refund status <select id="filter"><option value="approved">Approved — Awaiting Credit</option><option value="credited">Credited</option><option value="all">All Account Office Refunds</option></select></label><button id="refresh" class="btn secondary">Refresh</button></div><div class="table-wrap"><table class="app-table"><thead><tr><th>Matric Number</th><th>Student Name</th><th>Reference ID</th><th>Refund Amount</th><th>Approved At</th><th>Refund Status</th><th>Action</th></tr></thead><tbody id="rows"><tr><td colspan="7" class="empty-state">Loading approved refunds...</td></tr></tbody></table></div></section>
<dialog id="details" class="modal-dialog"><div class="modal-card"><header class="modal-header"><h2>Refund Details</h2><button class="modal-close" data-close>&times;</button></header><div class="modal-body" id="detail-body">Loading…</div><footer class="modal-footer"><button class="btn secondary" data-close>Close</button><button id="open-credit" class="btn primary" hidden>Mark as Credited</button></footer></div></dialog>
<dialog id="confirm" class="modal-dialog confirm-dialog"><div class="modal-card"><header class="modal-header"><h2>Confirm Refund Credit</h2></header><div class="modal-body"><p>Confirm that this refund has been credited to the student. This action will complete the refund process.</p><div class="callout-box" id="confirm-data"></div></div><footer class="modal-footer"><button id="cancel-credit" class="btn secondary">Cancel</button><button id="execute-credit" class="btn primary">Mark as Credited</button></footer></div></dialog>
</main></div><script>window.accountCsrf=<?=json_encode($csrf)?></script><script src="../assets/js/accountofficer.js"></script></body></html>
