<?php
declare(strict_types=1);
use CU\IdCard\{Identity,Lifecycle};
final class AccountOfficer {
    public function __construct(private PDO $db,private Lifecycle $lifecycle,private Identity $identity) {}
    private function out(bool $ok,string $message,mixed $data=null,int $code=200): never { http_response_code($code);header('Content-Type: application/json');echo json_encode(array_filter(['success'=>$ok,'message'=>$message,'data'=>$data],fn($v)=>$v!==null));exit; }
    private function clean(string $s): string { return trim(strip_tags($s)); }
    private function row(string $ref): array { $q=$this->db->prepare("SELECT a.applicationid,a.referencenumber,a.matricnumber,a.applicationtype,a.status applicationstatus,a.paymentstatus,a.paidat,s.full_name,s.department,s.programme,r.status refundstatus,r.amount,r.requestedat,r.requestedby,r.approvedat,r.approvedby,r.creditedat,r.creditedby FROM idcardapplications a JOIN idcardrefunds r ON r.applicationid=a.applicationid LEFT JOIN students s ON s.matric_no=a.matricnumber WHERE a.referencenumber=? LIMIT 1");$q->execute([$ref]);$x=$q->fetch();if(!$x)$this->out(false,'Approved refund not found.',null,404);return $x; }
    public function refunds(?string $search,?string $filter): never { $search=$this->clean($search??'');$filter=strtolower($this->clean($filter??'approved'));if(!in_array($filter,['approved','credited','all'],true))$filter='approved';$sql="SELECT a.referencenumber,a.matricnumber,a.status applicationstatus,a.paymentstatus,a.paidat,s.full_name,r.status refundstatus,r.amount,r.approvedat,r.creditedat FROM idcardrefunds r JOIN idcardapplications a ON a.applicationid=r.applicationid LEFT JOIN students s ON s.matric_no=a.matricnumber";$where=[];$p=[];if($filter!=='all'){$where[]='r.status=?';$p[]=$filter;}if($search!==''){$where[]='(a.referencenumber LIKE ? OR a.matricnumber LIKE ? OR s.full_name LIKE ?)';array_push($p,...array_fill(0,3,'%'.$search.'%'));}if($where)$sql.=' WHERE '.implode(' AND ',$where);$sql.=" ORDER BY CASE WHEN r.status='approved' THEN 0 ELSE 1 END,r.approvedat DESC";$q=$this->db->prepare($sql);$q->execute($p);$this->out(true,'Refunds retrieved.',$q->fetchAll()); }
    public function details(string $ref): never { $r=$this->row($this->clean($ref));$q=$this->db->prepare('SELECT paymentreference,paymentoptionname,baseamount,chargeamount,totalamount,currency,provider,status,paidat,completedat FROM paymenttransactions WHERE applicationid=? ORDER BY paymentid');$q->execute([$r['applicationid']]);$events=$this->lifecycle->history($this->identity,$r['referencenumber']);unset($r['applicationid']);$this->out(true,'Refund details retrieved.',['refund'=>$r,'transactions'=>$q->fetchAll(),'events'=>$events]); }
    public function credit(string $ref): never { $ref=$this->clean($ref);if($ref==='')$this->out(false,'Application reference is required.',null,400);try{$this->lifecycle->creditRefund($this->identity,$ref);$this->out(true,'Refund marked as credited.',['referencenumber'=>$ref,'refundstatus'=>'credited']);}catch(DomainException $e){$this->out(false,$e->getMessage(),null,409);}catch(Throwable $e){error_log('Refund credit error: '.$e->getMessage());$this->out(false,'Unable to credit this refund. Refresh and try again.',null,500);}}
}
